### PR TITLE
#0000001 naming  ObjectDumper, added ObjectDumper2

### PR DESCRIPTION
**Pull request by hvhaaren**
This change is [Reviewable](https://reviewable.io/reviews/jkbeks/reviewablerealtest/1)

### CODE REVIEW

**Comment by jkbeks** [comment]
zoveel?

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[101 LINQ Samples/description/Galleries.css, line 65 at r1](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1#-Kvl-mRn-ChKmoiPw0UY:-Kvl-mRn-ChKmoiPw0UZ:b32wtd) ([raw file](https://github.com/jkbeks/reviewablerealtest/blob/72594f795b99cac32353a652ce137b4fd4dca76b/101 LINQ Samples/description/Galleries.css#L65)):*
> ```CSS
> Description: The list of attached files under the editor
> ********************************/
> #fileAttachmentView {
> ```

ok

---

*[101 LINQ Samples/LINQ - Quantifiers/C#/Quantifiers/ObjectDumper.cs, line 15 at r1](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1#-Kvl-t54wu0QLmCVsmP4:-Kvl-t54wu0QLmCVsmP5:buv0l29) ([raw file](https://github.com/jkbeks/reviewablerealtest/blob/72594f795b99cac32353a652ce137b4fd4dca76b/101 LINQ Samples/LINQ - Quantifiers/C#/Quantifiers/ObjectDumper.cs#L15)):*
> ```Smalltalk
> public class ObjectDumper {
>     public static void Write(object value) {
>         Write(value, 0);
> ```

zinloos

---

*[101 LINQ Samples/LINQ - Quantifiers/C#/Quantifiers/ObjectDumper2.cs, line 13 at r1](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1#-Kvl-zcWeudnnghMiEhC:-Kvl-zcWeudnnghMiEhD:b3kre) ([raw file](https://github.com/jkbeks/reviewablerealtest/blob/72594f795b99cac32353a652ce137b4fd4dca76b/101 LINQ Samples/LINQ - Quantifiers/C#/Quantifiers/ObjectDumper2.cs#L13)):*
> ```Smalltalk
> using System.Reflection;
> 
> public class ObjectDumper2 {
> ```

?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1#-:-Kvl-gydE-OGrHGk7jcQ:bxtjzqn)*

**Comment by hvhaaren** [comment]
is nodig

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[101 LINQ Samples/LINQ - Quantifiers/C#/Quantifiers/ObjectDumper.cs, line 15 at r1](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1#-Kvl-t54wu0QLmCVsmP4:-Kvl0ERWCF42dFmYxwGr:b2ni8h5) ([raw file](https://github.com/jkbeks/reviewablerealtest/blob/72594f795b99cac32353a652ce137b4fd4dca76b/101 LINQ Samples/LINQ - Quantifiers/C#/Quantifiers/ObjectDumper.cs#L15)):*
<details><summary><i>Previously, jkbeks wrote…</i></summary><blockquote>

zinloos
</blockquote></details>

nee

---

*[101 LINQ Samples/LINQ - Quantifiers/C#/Quantifiers/ObjectDumper2.cs, line 13 at r1](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1#-Kvl-zcWeudnnghMiEhC:-Kvl0GXRFmGJA0Ozy-vL:b-pz9wq6) ([raw file](https://github.com/jkbeks/reviewablerealtest/blob/72594f795b99cac32353a652ce137b4fd4dca76b/101 LINQ Samples/LINQ - Quantifiers/C#/Quantifiers/ObjectDumper2.cs#L13)):*
<details><summary><i>Previously, jkbeks wrote…</i></summary><blockquote>

?
</blockquote></details>

handig

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1#-:-Kvl0ApzfCYlHtgiKSZr:b8cjbg0)*

**Comment by jkbeks** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[101 LINQ Samples/description/Galleries.css, line 65 at r1](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1#-Kvl-mRn-ChKmoiPw0UY:-Kvl0Xg9NoV16c2pe7zn:bb7ktj5) ([raw file](https://github.com/jkbeks/reviewablerealtest/blob/72594f795b99cac32353a652ce137b4fd4dca76b/101 LINQ Samples/description/Galleries.css#L65)):*
<details><summary><i>Previously, jkbeks wrote…</i></summary><blockquote>

ok
</blockquote></details>

mooi

---

*[101 LINQ Samples/LINQ - Quantifiers/C#/Quantifiers/ObjectDumper.cs, line 15 at r1](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1#-Kvl-t54wu0QLmCVsmP4:-Kvl0eB4cHHXzX6PLg6r:b-3w1te9) ([raw file](https://github.com/jkbeks/reviewablerealtest/blob/72594f795b99cac32353a652ce137b4fd4dca76b/101 LINQ Samples/LINQ - Quantifiers/C#/Quantifiers/ObjectDumper.cs#L15)):*
<details><summary><i>Previously, hvhaaren wrote…</i></summary><blockquote>

nee
</blockquote></details>

vind van wel

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1)*

**Comment by hvhaaren** [comment]
hernoemd naar dumper3

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[101 LINQ Samples/LINQ - Quantifiers/C#/Quantifiers/ObjectDumper.cs, line 15 at r1](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1#-Kvl-t54wu0QLmCVsmP4:-Kvl2sdLljQXiqCSquu3:b-896fix) ([raw file](https://github.com/jkbeks/reviewablerealtest/blob/72594f795b99cac32353a652ce137b4fd4dca76b/101 LINQ Samples/LINQ - Quantifiers/C#/Quantifiers/ObjectDumper.cs#L15)):*
<details><summary><i>Previously, jkbeks wrote…</i></summary><blockquote>

vind van wel
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1#-:-Kvl3-hoZvOecoco_vcj:bd4t5cb)*

**Comment by hvhaaren** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[101 LINQ Samples/description/Galleries.css, line 65 at r1](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1#-Kvl-mRn-ChKmoiPw0UY:-Kvl3K9uCR0MihlKtN93:b-896fix) ([raw file](https://github.com/jkbeks/reviewablerealtest/blob/72594f795b99cac32353a652ce137b4fd4dca76b/101 LINQ Samples/description/Galleries.css#L65)):*
<details><summary><i>Previously, jkbeks wrote…</i></summary><blockquote>

mooi
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1)*

**Comment by jkbeks** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1#-:-Kvl3uePNJczRsoU9mHQ:bnfp4nl)*

**Comment by jkbeks** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1)*

**Comment by jkbeks** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1#-Kvl4cCdsGMQGId2hDQN:-Kvl4cCdsGMQGId2hDQO:bsgv8sz) (no related file):*
toch niet mee eens

---

*[101 LINQ Samples/LINQ - Quantifiers/C#/Quantifiers/ObjectDumper2.cs, line 13 at r1](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1#-Kvl-zcWeudnnghMiEhC:-Kvl4jnI2cGeIR9XdW98:bes4t3a) ([raw file](https://github.com/jkbeks/reviewablerealtest/blob/72594f795b99cac32353a652ce137b4fd4dca76b/101 LINQ Samples/LINQ - Quantifiers/C#/Quantifiers/ObjectDumper2.cs#L13)):*
<details><summary><i>Previously, hvhaaren wrote…</i></summary><blockquote>

handig
</blockquote></details>

opnieuw

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1)*

**Comment by hvhaaren** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[101 LINQ Samples/LINQ - Quantifiers/C#/Quantifiers/ObjectDumper2.cs, line 13 at r1](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1#-Kvl-zcWeudnnghMiEhC:-Kvl4sfC7CuVKtypSlar:b-232fm3) ([raw file](https://github.com/jkbeks/reviewablerealtest/blob/72594f795b99cac32353a652ce137b4fd4dca76b/101 LINQ Samples/LINQ - Quantifiers/C#/Quantifiers/ObjectDumper2.cs#L13)):*
<details><summary><i>Previously, jkbeks wrote…</i></summary><blockquote>

opnieuw
</blockquote></details>

bekeken en klopt toch wel

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1)*

**Comment by hvhaaren** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1#-Kvl4cCdsGMQGId2hDQN:-Kvl5AKRUF-kMsQPJQNX:b-xv8m8b) (no related file):*
<details><summary><i>Previously, jkbeks wrote…</i></summary><blockquote>

toch niet mee eens
</blockquote></details>

zie discussie in code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/1)*

**Pull request merged**
