### PR TITLE
hbs conversion operators

### PR DESCRIPTION
**Pull request by jkbeks**
This change is [Reviewable](https://reviewable.io/reviews/jkbeks/reviewablerealtest/2)

### CODE REVIEW

**Comment by hvhaaren** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[101 LINQ Samples/LINQ - Conversion Operators/C#/ConversionOperators/Program.cs, line 20 at r1](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/2#-KuYL5ATKC-JPoscdXxH:-KuYL5ATKC-JPoscdXxI:b-nd2xhx) ([raw file](https://github.com/jkbeks/reviewablerealtest/blob/93eafce96105be83f98d8d8a2fe301c85ee02f7d/101 LINQ Samples/LINQ - Conversion Operators/C#/ConversionOperators/Program.cs#L20)):*
> ```Smalltalk
> 
> 			//samples.Linq56(); // This sample uses ToDictionary to immediately  evaluate a  sequence  and a related key expression into a dictionary
> 			samples.Linq56b();
> ```

Waarom is de letter b nodig?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/2)*

**Comment by jkbeks** [comment]
*[101 LINQ Samples/LINQ - Conversion Operators/C#/ConversionOperators/Program.cs, line 20 at r1](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/2#-KuYL5ATKC-JPoscdXxH:-Kvkwdu5M2xHkYorKs7S:bxqvrhk) ([raw file](https://github.com/jkbeks/reviewablerealtest/blob/93eafce96105be83f98d8d8a2fe301c85ee02f7d/101 LINQ Samples/LINQ - Conversion Operators/C#/ConversionOperators/Program.cs#L20)):*
<details><summary><i>Previously, hvhaaren wrote…</i></summary><blockquote>

Waarom is de letter b nodig?
</blockquote></details>

anders had ik nummer 102 moeten gebruiken

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/2)*

**Comment by hvhaaren** [comment]
*[101 LINQ Samples/LINQ - Conversion Operators/C#/ConversionOperators/Program.cs, line 20 at r1](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/2#-KuYL5ATKC-JPoscdXxH:-KvkxBEREcd7k4wwYBZl:b8ud0qq) ([raw file](https://github.com/jkbeks/reviewablerealtest/blob/93eafce96105be83f98d8d8a2fe301c85ee02f7d/101 LINQ Samples/LINQ - Conversion Operators/C#/ConversionOperators/Program.cs#L20)):*
<details><summary><i>Previously, jkbeks wrote…</i></summary><blockquote>

anders had ik nummer 102 moeten gebruiken
</blockquote></details>

is 102 niet beter dan?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/2)*

**Comment by jkbeks** [comment]
*[101 LINQ Samples/LINQ - Conversion Operators/C#/ConversionOperators/Program.cs, line 20 at r1](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/2#-KuYL5ATKC-JPoscdXxH:-Kvkxa51XXc3GAuzzVe5:b-896fix) ([raw file](https://github.com/jkbeks/reviewablerealtest/blob/93eafce96105be83f98d8d8a2fe301c85ee02f7d/101 LINQ Samples/LINQ - Conversion Operators/C#/ConversionOperators/Program.cs#L20)):*
<details><summary><i>Previously, hvhaaren wrote…</i></summary><blockquote>

is 102 niet beter dan?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/2)*

**Comment by hvhaaren** [comment]
*[101 LINQ Samples/LINQ - Conversion Operators/C#/ConversionOperators/Program.cs, line 95 at r1](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/2#-Kvkz0thvhqLlSBrkIUL:-Kvkz0thvhqLlSBrkIUM:b-iyvhz2) ([raw file](https://github.com/jkbeks/reviewablerealtest/blob/93eafce96105be83f98d8d8a2fe301c85ee02f7d/101 LINQ Samples/LINQ - Conversion Operators/C#/ConversionOperators/Program.cs#L95)):*
> ```Smalltalk
> 					Console.WriteLine("3 = " + item);
> 				}
> ```

whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/2)*

**Comment by hvhaaren** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jkbeks/reviewablerealtest/2)*

**Pull request merged**
